// <auto-generated />
using System;
using JobsCatalog.Persistance.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobsCatalog.Persistance.Migrations
{
    [DbContext(typeof(JobsCatalogDbContextTransaction))]
    partial class JobsCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JobsCatalog.Domain.Dictionaries.ExperienceLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExperienceLeves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Junior"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mid"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Senior"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Expert"
                        });
                });

            modelBuilder.Entity("JobsCatalog.Domain.Dictionaries.ProgrammingLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "CSharp",
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Image = "Java",
                            Name = "Java"
                        },
                        new
                        {
                            Id = 3,
                            Image = "Python",
                            Name = "Python"
                        },
                        new
                        {
                            Id = 4,
                            Image = "JavaScript",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 5,
                            Image = "CPlusPlus",
                            Name = "C++"
                        });
                });

            modelBuilder.Entity("JobsCatalog.Domain.Dictionaries.Technology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ASP.Net"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Entity Framwork"
                        },
                        new
                        {
                            Id = 4,
                            Name = "HTML"
                        },
                        new
                        {
                            Id = 5,
                            Name = "CSS"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Azure"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 8,
                            Name = "React"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Hibernate"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Spring"
                        },
                        new
                        {
                            Id = 12,
                            Name = "JUnit"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Mockito"
                        },
                        new
                        {
                            Id = 14,
                            Name = "XUnit"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Moq"
                        },
                        new
                        {
                            Id = 16,
                            Name = "AWS"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Flask"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Django"
                        },
                        new
                        {
                            Id = 19,
                            Name = "C++ 17"
                        });
                });

            modelBuilder.Entity("JobsCatalog.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Inactivated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Modified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyLogo = "SoftwareSolution",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 165, DateTimeKind.Unspecified).AddTicks(770), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 165, DateTimeKind.Unspecified).AddTicks(770), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Name = "Software Solution",
                            ShortDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dignissim nulla tempor, varius neque at, bibendum mi. Suspendisse efficitur blandit pharetra. Quisque non commodo ante, ut volutpat arcu. Vestibulum mi magna, commodo nec dolor vitae, gravida sagittis nisi. Phasellus vulputate, dolor eget cursus dignissim, ligula augue porta ante, sit amet semper lacus enim ac tortor. Nullam congue auctor erat, volutpat pharetra tellus pretium dignissim.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompanyLogo = "SwissUnionBank",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 165, DateTimeKind.Unspecified).AddTicks(770), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 165, DateTimeKind.Unspecified).AddTicks(770), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Name = "Swiss Union Bank",
                            ShortDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dignissim nulla tempor, varius neque at, bibendum mi. Suspendisse efficitur blandit pharetra. Quisque non commodo ante, ut volutpat arcu. Vestibulum mi magna, commodo nec dolor vitae, gravida sagittis nisi. Phasellus vulputate, dolor eget cursus dignissim, ligula augue porta ante, sit amet semper lacus enim ac tortor. Nullam congue auctor erat, volutpat pharetra tellus pretium dignissim.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 3,
                            CompanyLogo = "Creativity",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 165, DateTimeKind.Unspecified).AddTicks(770), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 165, DateTimeKind.Unspecified).AddTicks(770), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Name = "Creativity",
                            ShortDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dignissim nulla tempor, varius neque at, bibendum mi. Suspendisse efficitur blandit pharetra. Quisque non commodo ante, ut volutpat arcu. Vestibulum mi magna, commodo nec dolor vitae, gravida sagittis nisi. Phasellus vulputate, dolor eget cursus dignissim, ligula augue porta ante, sit amet semper lacus enim ac tortor. Nullam congue auctor erat, volutpat pharetra tellus pretium dignissim.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 4,
                            CompanyLogo = "ItOpportunity",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 165, DateTimeKind.Unspecified).AddTicks(770), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 165, DateTimeKind.Unspecified).AddTicks(770), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Name = "It Opportunity",
                            ShortDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dignissim nulla tempor, varius neque at, bibendum mi. Suspendisse efficitur blandit pharetra. Quisque non commodo ante, ut volutpat arcu. Vestibulum mi magna, commodo nec dolor vitae, gravida sagittis nisi. Phasellus vulputate, dolor eget cursus dignissim, ligula augue porta ante, sit amet semper lacus enim ac tortor. Nullam congue auctor erat, volutpat pharetra tellus pretium dignissim.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 5,
                            CompanyLogo = "SoftMatter",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 165, DateTimeKind.Unspecified).AddTicks(770), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 165, DateTimeKind.Unspecified).AddTicks(770), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Name = "Soft Matter",
                            ShortDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dignissim nulla tempor, varius neque at, bibendum mi. Suspendisse efficitur blandit pharetra. Quisque non commodo ante, ut volutpat arcu. Vestibulum mi magna, commodo nec dolor vitae, gravida sagittis nisi. Phasellus vulputate, dolor eget cursus dignissim, ligula augue porta ante, sit amet semper lacus enim ac tortor. Nullam congue auctor erat, volutpat pharetra tellus pretium dignissim.",
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("JobsCatalog.Domain.Entities.JobDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expectation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Inactivated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobOfferId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Modified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Offer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobOfferId")
                        .IsUnique();

                    b.ToTable("JobDescriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id viverra erat. Nulla euismod laoreet metus vitae mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla maximus libero non elementum congue. Vestibulum dignissim pellentesque mauris non molestie. Aliquam neque ligula, rutrum at tincidunt ut, fringilla posuere risus. Aenean porta convallis turpis, et ornare nisl finibus ac. Maecenas volutpat tortor vel sagittis aliquam.",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Expectation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Nam ut justo id nisl egestas mattis.Proin ac ipsum eget velit varius pretium.Nam porta ligula vitae diam auctor dictum.Nulla varius nunc in velit ultrices ullamcorper.",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JobOfferId = 1,
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Offer = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas in lacus id ex iaculis iaculis vel ac metus.Morbi ut tellus accumsan, vehicula mi volutpat, lobortis leo.Aenean sodales massa ac risus tincidunt, in malesuada est tincidunt.Donec eget turpis tincidunt, tempus erat at, venenatis erat.Duis ultricies dui ac tempor placerat.Cras sollicitudin ligula in turpis aliquam luctus at quis lacus.",
                            Responsibilities = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem lorem, volutpat facilisis fringilla et, molestie in nunc. Cras ac nunc imperdiet, euismod lorem vitae, maximus nulla. Etiam porttitor elit vitae purus dapibus consectetur. Fusce imperdiet turpis a lectus scelerisque, vel ultrices odio vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque nisi nisl, fringilla in luctus eget, cursus congue augue. Integer condimentum sollicitudin nunc in tristique. Integer id justo leo. Morbi vel lacus sagittis, venenatis ex eget, porta risus. Nunc suscipit dignissim magna at commodo. Sed iaculis, turpis quis ornare luctus, massa orci tempor tellus, consequat gravida nisi nibh et dui. Integer eu metus sem. Morbi auctor ex est, vel aliquam arcu vulputate eu. Fusce aliquam eros quis ipsum iaculis aliquet. Nullam et auctor lorem, sit amet tempor lorem. Praesent nec nisl in ipsum accumsan sollicitudin.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            About = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id viverra erat. Nulla euismod laoreet metus vitae mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla maximus libero non elementum congue. Vestibulum dignissim pellentesque mauris non molestie. Aliquam neque ligula, rutrum at tincidunt ut, fringilla posuere risus. Aenean porta convallis turpis, et ornare nisl finibus ac. Maecenas volutpat tortor vel sagittis aliquam.",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Expectation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Nam ut justo id nisl egestas mattis.Proin ac ipsum eget velit varius pretium.Nam porta ligula vitae diam auctor dictum.Nulla varius nunc in velit ultrices ullamcorper.",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JobOfferId = 2,
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Offer = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas in lacus id ex iaculis iaculis vel ac metus.Morbi ut tellus accumsan, vehicula mi volutpat, lobortis leo.Aenean sodales massa ac risus tincidunt, in malesuada est tincidunt.Donec eget turpis tincidunt, tempus erat at, venenatis erat.Duis ultricies dui ac tempor placerat.Cras sollicitudin ligula in turpis aliquam luctus at quis lacus.",
                            Responsibilities = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem lorem, volutpat facilisis fringilla et, molestie in nunc. Cras ac nunc imperdiet, euismod lorem vitae, maximus nulla. Etiam porttitor elit vitae purus dapibus consectetur. Fusce imperdiet turpis a lectus scelerisque, vel ultrices odio vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque nisi nisl, fringilla in luctus eget, cursus congue augue. Integer condimentum sollicitudin nunc in tristique. Integer id justo leo. Morbi vel lacus sagittis, venenatis ex eget, porta risus. Nunc suscipit dignissim magna at commodo. Sed iaculis, turpis quis ornare luctus, massa orci tempor tellus, consequat gravida nisi nibh et dui. Integer eu metus sem. Morbi auctor ex est, vel aliquam arcu vulputate eu. Fusce aliquam eros quis ipsum iaculis aliquet. Nullam et auctor lorem, sit amet tempor lorem. Praesent nec nisl in ipsum accumsan sollicitudin.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 3,
                            About = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id viverra erat. Nulla euismod laoreet metus vitae mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla maximus libero non elementum congue. Vestibulum dignissim pellentesque mauris non molestie. Aliquam neque ligula, rutrum at tincidunt ut, fringilla posuere risus. Aenean porta convallis turpis, et ornare nisl finibus ac. Maecenas volutpat tortor vel sagittis aliquam.",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Expectation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Nam ut justo id nisl egestas mattis.Proin ac ipsum eget velit varius pretium.Nam porta ligula vitae diam auctor dictum.Nulla varius nunc in velit ultrices ullamcorper.",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JobOfferId = 3,
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Offer = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas in lacus id ex iaculis iaculis vel ac metus.Morbi ut tellus accumsan, vehicula mi volutpat, lobortis leo.Aenean sodales massa ac risus tincidunt, in malesuada est tincidunt.Donec eget turpis tincidunt, tempus erat at, venenatis erat.Duis ultricies dui ac tempor placerat.Cras sollicitudin ligula in turpis aliquam luctus at quis lacus.",
                            Responsibilities = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem lorem, volutpat facilisis fringilla et, molestie in nunc. Cras ac nunc imperdiet, euismod lorem vitae, maximus nulla. Etiam porttitor elit vitae purus dapibus consectetur. Fusce imperdiet turpis a lectus scelerisque, vel ultrices odio vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque nisi nisl, fringilla in luctus eget, cursus congue augue. Integer condimentum sollicitudin nunc in tristique. Integer id justo leo. Morbi vel lacus sagittis, venenatis ex eget, porta risus. Nunc suscipit dignissim magna at commodo. Sed iaculis, turpis quis ornare luctus, massa orci tempor tellus, consequat gravida nisi nibh et dui. Integer eu metus sem. Morbi auctor ex est, vel aliquam arcu vulputate eu. Fusce aliquam eros quis ipsum iaculis aliquet. Nullam et auctor lorem, sit amet tempor lorem. Praesent nec nisl in ipsum accumsan sollicitudin.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 4,
                            About = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id viverra erat. Nulla euismod laoreet metus vitae mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla maximus libero non elementum congue. Vestibulum dignissim pellentesque mauris non molestie. Aliquam neque ligula, rutrum at tincidunt ut, fringilla posuere risus. Aenean porta convallis turpis, et ornare nisl finibus ac. Maecenas volutpat tortor vel sagittis aliquam.",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Expectation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Nam ut justo id nisl egestas mattis.Proin ac ipsum eget velit varius pretium.Nam porta ligula vitae diam auctor dictum.Nulla varius nunc in velit ultrices ullamcorper.",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JobOfferId = 4,
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Offer = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas in lacus id ex iaculis iaculis vel ac metus.Morbi ut tellus accumsan, vehicula mi volutpat, lobortis leo.Aenean sodales massa ac risus tincidunt, in malesuada est tincidunt.Donec eget turpis tincidunt, tempus erat at, venenatis erat.Duis ultricies dui ac tempor placerat.Cras sollicitudin ligula in turpis aliquam luctus at quis lacus.",
                            Responsibilities = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem lorem, volutpat facilisis fringilla et, molestie in nunc. Cras ac nunc imperdiet, euismod lorem vitae, maximus nulla. Etiam porttitor elit vitae purus dapibus consectetur. Fusce imperdiet turpis a lectus scelerisque, vel ultrices odio vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque nisi nisl, fringilla in luctus eget, cursus congue augue. Integer condimentum sollicitudin nunc in tristique. Integer id justo leo. Morbi vel lacus sagittis, venenatis ex eget, porta risus. Nunc suscipit dignissim magna at commodo. Sed iaculis, turpis quis ornare luctus, massa orci tempor tellus, consequat gravida nisi nibh et dui. Integer eu metus sem. Morbi auctor ex est, vel aliquam arcu vulputate eu. Fusce aliquam eros quis ipsum iaculis aliquet. Nullam et auctor lorem, sit amet tempor lorem. Praesent nec nisl in ipsum accumsan sollicitudin.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 5,
                            About = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id viverra erat. Nulla euismod laoreet metus vitae mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla maximus libero non elementum congue. Vestibulum dignissim pellentesque mauris non molestie. Aliquam neque ligula, rutrum at tincidunt ut, fringilla posuere risus. Aenean porta convallis turpis, et ornare nisl finibus ac. Maecenas volutpat tortor vel sagittis aliquam.",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Expectation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Nam ut justo id nisl egestas mattis.Proin ac ipsum eget velit varius pretium.Nam porta ligula vitae diam auctor dictum.Nulla varius nunc in velit ultrices ullamcorper.",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JobOfferId = 5,
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Offer = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas in lacus id ex iaculis iaculis vel ac metus.Morbi ut tellus accumsan, vehicula mi volutpat, lobortis leo.Aenean sodales massa ac risus tincidunt, in malesuada est tincidunt.Donec eget turpis tincidunt, tempus erat at, venenatis erat.Duis ultricies dui ac tempor placerat.Cras sollicitudin ligula in turpis aliquam luctus at quis lacus.",
                            Responsibilities = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem lorem, volutpat facilisis fringilla et, molestie in nunc. Cras ac nunc imperdiet, euismod lorem vitae, maximus nulla. Etiam porttitor elit vitae purus dapibus consectetur. Fusce imperdiet turpis a lectus scelerisque, vel ultrices odio vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque nisi nisl, fringilla in luctus eget, cursus congue augue. Integer condimentum sollicitudin nunc in tristique. Integer id justo leo. Morbi vel lacus sagittis, venenatis ex eget, porta risus. Nunc suscipit dignissim magna at commodo. Sed iaculis, turpis quis ornare luctus, massa orci tempor tellus, consequat gravida nisi nibh et dui. Integer eu metus sem. Morbi auctor ex est, vel aliquam arcu vulputate eu. Fusce aliquam eros quis ipsum iaculis aliquet. Nullam et auctor lorem, sit amet tempor lorem. Praesent nec nisl in ipsum accumsan sollicitudin.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 6,
                            About = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id viverra erat. Nulla euismod laoreet metus vitae mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla maximus libero non elementum congue. Vestibulum dignissim pellentesque mauris non molestie. Aliquam neque ligula, rutrum at tincidunt ut, fringilla posuere risus. Aenean porta convallis turpis, et ornare nisl finibus ac. Maecenas volutpat tortor vel sagittis aliquam.",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Expectation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Nam ut justo id nisl egestas mattis.Proin ac ipsum eget velit varius pretium.Nam porta ligula vitae diam auctor dictum.Nulla varius nunc in velit ultrices ullamcorper.",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JobOfferId = 6,
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Offer = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas in lacus id ex iaculis iaculis vel ac metus.Morbi ut tellus accumsan, vehicula mi volutpat, lobortis leo.Aenean sodales massa ac risus tincidunt, in malesuada est tincidunt.Donec eget turpis tincidunt, tempus erat at, venenatis erat.Duis ultricies dui ac tempor placerat.Cras sollicitudin ligula in turpis aliquam luctus at quis lacus.",
                            Responsibilities = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem lorem, volutpat facilisis fringilla et, molestie in nunc. Cras ac nunc imperdiet, euismod lorem vitae, maximus nulla. Etiam porttitor elit vitae purus dapibus consectetur. Fusce imperdiet turpis a lectus scelerisque, vel ultrices odio vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque nisi nisl, fringilla in luctus eget, cursus congue augue. Integer condimentum sollicitudin nunc in tristique. Integer id justo leo. Morbi vel lacus sagittis, venenatis ex eget, porta risus. Nunc suscipit dignissim magna at commodo. Sed iaculis, turpis quis ornare luctus, massa orci tempor tellus, consequat gravida nisi nibh et dui. Integer eu metus sem. Morbi auctor ex est, vel aliquam arcu vulputate eu. Fusce aliquam eros quis ipsum iaculis aliquet. Nullam et auctor lorem, sit amet tempor lorem. Praesent nec nisl in ipsum accumsan sollicitudin.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 7,
                            About = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id viverra erat. Nulla euismod laoreet metus vitae mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla maximus libero non elementum congue. Vestibulum dignissim pellentesque mauris non molestie. Aliquam neque ligula, rutrum at tincidunt ut, fringilla posuere risus. Aenean porta convallis turpis, et ornare nisl finibus ac. Maecenas volutpat tortor vel sagittis aliquam.",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Expectation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Nam ut justo id nisl egestas mattis.Proin ac ipsum eget velit varius pretium.Nam porta ligula vitae diam auctor dictum.Nulla varius nunc in velit ultrices ullamcorper.",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JobOfferId = 7,
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Offer = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas in lacus id ex iaculis iaculis vel ac metus.Morbi ut tellus accumsan, vehicula mi volutpat, lobortis leo.Aenean sodales massa ac risus tincidunt, in malesuada est tincidunt.Donec eget turpis tincidunt, tempus erat at, venenatis erat.Duis ultricies dui ac tempor placerat.Cras sollicitudin ligula in turpis aliquam luctus at quis lacus.",
                            Responsibilities = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem lorem, volutpat facilisis fringilla et, molestie in nunc. Cras ac nunc imperdiet, euismod lorem vitae, maximus nulla. Etiam porttitor elit vitae purus dapibus consectetur. Fusce imperdiet turpis a lectus scelerisque, vel ultrices odio vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque nisi nisl, fringilla in luctus eget, cursus congue augue. Integer condimentum sollicitudin nunc in tristique. Integer id justo leo. Morbi vel lacus sagittis, venenatis ex eget, porta risus. Nunc suscipit dignissim magna at commodo. Sed iaculis, turpis quis ornare luctus, massa orci tempor tellus, consequat gravida nisi nibh et dui. Integer eu metus sem. Morbi auctor ex est, vel aliquam arcu vulputate eu. Fusce aliquam eros quis ipsum iaculis aliquet. Nullam et auctor lorem, sit amet tempor lorem. Praesent nec nisl in ipsum accumsan sollicitudin.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 8,
                            About = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id viverra erat. Nulla euismod laoreet metus vitae mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla maximus libero non elementum congue. Vestibulum dignissim pellentesque mauris non molestie. Aliquam neque ligula, rutrum at tincidunt ut, fringilla posuere risus. Aenean porta convallis turpis, et ornare nisl finibus ac. Maecenas volutpat tortor vel sagittis aliquam.",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Expectation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Nam ut justo id nisl egestas mattis.Proin ac ipsum eget velit varius pretium.Nam porta ligula vitae diam auctor dictum.Nulla varius nunc in velit ultrices ullamcorper.",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JobOfferId = 8,
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Offer = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas in lacus id ex iaculis iaculis vel ac metus.Morbi ut tellus accumsan, vehicula mi volutpat, lobortis leo.Aenean sodales massa ac risus tincidunt, in malesuada est tincidunt.Donec eget turpis tincidunt, tempus erat at, venenatis erat.Duis ultricies dui ac tempor placerat.Cras sollicitudin ligula in turpis aliquam luctus at quis lacus.",
                            Responsibilities = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem lorem, volutpat facilisis fringilla et, molestie in nunc. Cras ac nunc imperdiet, euismod lorem vitae, maximus nulla. Etiam porttitor elit vitae purus dapibus consectetur. Fusce imperdiet turpis a lectus scelerisque, vel ultrices odio vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque nisi nisl, fringilla in luctus eget, cursus congue augue. Integer condimentum sollicitudin nunc in tristique. Integer id justo leo. Morbi vel lacus sagittis, venenatis ex eget, porta risus. Nunc suscipit dignissim magna at commodo. Sed iaculis, turpis quis ornare luctus, massa orci tempor tellus, consequat gravida nisi nibh et dui. Integer eu metus sem. Morbi auctor ex est, vel aliquam arcu vulputate eu. Fusce aliquam eros quis ipsum iaculis aliquet. Nullam et auctor lorem, sit amet tempor lorem. Praesent nec nisl in ipsum accumsan sollicitudin.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 9,
                            About = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id viverra erat. Nulla euismod laoreet metus vitae mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla maximus libero non elementum congue. Vestibulum dignissim pellentesque mauris non molestie. Aliquam neque ligula, rutrum at tincidunt ut, fringilla posuere risus. Aenean porta convallis turpis, et ornare nisl finibus ac. Maecenas volutpat tortor vel sagittis aliquam.",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Expectation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Nam ut justo id nisl egestas mattis.Proin ac ipsum eget velit varius pretium.Nam porta ligula vitae diam auctor dictum.Nulla varius nunc in velit ultrices ullamcorper.",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JobOfferId = 9,
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Offer = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas in lacus id ex iaculis iaculis vel ac metus.Morbi ut tellus accumsan, vehicula mi volutpat, lobortis leo.Aenean sodales massa ac risus tincidunt, in malesuada est tincidunt.Donec eget turpis tincidunt, tempus erat at, venenatis erat.Duis ultricies dui ac tempor placerat.Cras sollicitudin ligula in turpis aliquam luctus at quis lacus.",
                            Responsibilities = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem lorem, volutpat facilisis fringilla et, molestie in nunc. Cras ac nunc imperdiet, euismod lorem vitae, maximus nulla. Etiam porttitor elit vitae purus dapibus consectetur. Fusce imperdiet turpis a lectus scelerisque, vel ultrices odio vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque nisi nisl, fringilla in luctus eget, cursus congue augue. Integer condimentum sollicitudin nunc in tristique. Integer id justo leo. Morbi vel lacus sagittis, venenatis ex eget, porta risus. Nunc suscipit dignissim magna at commodo. Sed iaculis, turpis quis ornare luctus, massa orci tempor tellus, consequat gravida nisi nibh et dui. Integer eu metus sem. Morbi auctor ex est, vel aliquam arcu vulputate eu. Fusce aliquam eros quis ipsum iaculis aliquet. Nullam et auctor lorem, sit amet tempor lorem. Praesent nec nisl in ipsum accumsan sollicitudin.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 10,
                            About = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id viverra erat. Nulla euismod laoreet metus vitae mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla maximus libero non elementum congue. Vestibulum dignissim pellentesque mauris non molestie. Aliquam neque ligula, rutrum at tincidunt ut, fringilla posuere risus. Aenean porta convallis turpis, et ornare nisl finibus ac. Maecenas volutpat tortor vel sagittis aliquam.",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Expectation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Nam ut justo id nisl egestas mattis.Proin ac ipsum eget velit varius pretium.Nam porta ligula vitae diam auctor dictum.Nulla varius nunc in velit ultrices ullamcorper.",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JobOfferId = 10,
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Offer = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas in lacus id ex iaculis iaculis vel ac metus.Morbi ut tellus accumsan, vehicula mi volutpat, lobortis leo.Aenean sodales massa ac risus tincidunt, in malesuada est tincidunt.Donec eget turpis tincidunt, tempus erat at, venenatis erat.Duis ultricies dui ac tempor placerat.Cras sollicitudin ligula in turpis aliquam luctus at quis lacus.",
                            Responsibilities = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem lorem, volutpat facilisis fringilla et, molestie in nunc. Cras ac nunc imperdiet, euismod lorem vitae, maximus nulla. Etiam porttitor elit vitae purus dapibus consectetur. Fusce imperdiet turpis a lectus scelerisque, vel ultrices odio vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque nisi nisl, fringilla in luctus eget, cursus congue augue. Integer condimentum sollicitudin nunc in tristique. Integer id justo leo. Morbi vel lacus sagittis, venenatis ex eget, porta risus. Nunc suscipit dignissim magna at commodo. Sed iaculis, turpis quis ornare luctus, massa orci tempor tellus, consequat gravida nisi nibh et dui. Integer eu metus sem. Morbi auctor ex est, vel aliquam arcu vulputate eu. Fusce aliquam eros quis ipsum iaculis aliquet. Nullam et auctor lorem, sit amet tempor lorem. Praesent nec nisl in ipsum accumsan sollicitudin.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 11,
                            About = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id viverra erat. Nulla euismod laoreet metus vitae mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla maximus libero non elementum congue. Vestibulum dignissim pellentesque mauris non molestie. Aliquam neque ligula, rutrum at tincidunt ut, fringilla posuere risus. Aenean porta convallis turpis, et ornare nisl finibus ac. Maecenas volutpat tortor vel sagittis aliquam.",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Expectation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Nam ut justo id nisl egestas mattis.Proin ac ipsum eget velit varius pretium.Nam porta ligula vitae diam auctor dictum.Nulla varius nunc in velit ultrices ullamcorper.",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JobOfferId = 11,
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Offer = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas in lacus id ex iaculis iaculis vel ac metus.Morbi ut tellus accumsan, vehicula mi volutpat, lobortis leo.Aenean sodales massa ac risus tincidunt, in malesuada est tincidunt.Donec eget turpis tincidunt, tempus erat at, venenatis erat.Duis ultricies dui ac tempor placerat.Cras sollicitudin ligula in turpis aliquam luctus at quis lacus.",
                            Responsibilities = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem lorem, volutpat facilisis fringilla et, molestie in nunc. Cras ac nunc imperdiet, euismod lorem vitae, maximus nulla. Etiam porttitor elit vitae purus dapibus consectetur. Fusce imperdiet turpis a lectus scelerisque, vel ultrices odio vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque nisi nisl, fringilla in luctus eget, cursus congue augue. Integer condimentum sollicitudin nunc in tristique. Integer id justo leo. Morbi vel lacus sagittis, venenatis ex eget, porta risus. Nunc suscipit dignissim magna at commodo. Sed iaculis, turpis quis ornare luctus, massa orci tempor tellus, consequat gravida nisi nibh et dui. Integer eu metus sem. Morbi auctor ex est, vel aliquam arcu vulputate eu. Fusce aliquam eros quis ipsum iaculis aliquet. Nullam et auctor lorem, sit amet tempor lorem. Praesent nec nisl in ipsum accumsan sollicitudin.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 12,
                            About = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id viverra erat. Nulla euismod laoreet metus vitae mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla maximus libero non elementum congue. Vestibulum dignissim pellentesque mauris non molestie. Aliquam neque ligula, rutrum at tincidunt ut, fringilla posuere risus. Aenean porta convallis turpis, et ornare nisl finibus ac. Maecenas volutpat tortor vel sagittis aliquam.",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Expectation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Nam ut justo id nisl egestas mattis.Proin ac ipsum eget velit varius pretium.Nam porta ligula vitae diam auctor dictum.Nulla varius nunc in velit ultrices ullamcorper.",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JobOfferId = 12,
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Offer = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas in lacus id ex iaculis iaculis vel ac metus.Morbi ut tellus accumsan, vehicula mi volutpat, lobortis leo.Aenean sodales massa ac risus tincidunt, in malesuada est tincidunt.Donec eget turpis tincidunt, tempus erat at, venenatis erat.Duis ultricies dui ac tempor placerat.Cras sollicitudin ligula in turpis aliquam luctus at quis lacus.",
                            Responsibilities = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem lorem, volutpat facilisis fringilla et, molestie in nunc. Cras ac nunc imperdiet, euismod lorem vitae, maximus nulla. Etiam porttitor elit vitae purus dapibus consectetur. Fusce imperdiet turpis a lectus scelerisque, vel ultrices odio vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque nisi nisl, fringilla in luctus eget, cursus congue augue. Integer condimentum sollicitudin nunc in tristique. Integer id justo leo. Morbi vel lacus sagittis, venenatis ex eget, porta risus. Nunc suscipit dignissim magna at commodo. Sed iaculis, turpis quis ornare luctus, massa orci tempor tellus, consequat gravida nisi nibh et dui. Integer eu metus sem. Morbi auctor ex est, vel aliquam arcu vulputate eu. Fusce aliquam eros quis ipsum iaculis aliquet. Nullam et auctor lorem, sit amet tempor lorem. Praesent nec nisl in ipsum accumsan sollicitudin.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 13,
                            About = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id viverra erat. Nulla euismod laoreet metus vitae mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla maximus libero non elementum congue. Vestibulum dignissim pellentesque mauris non molestie. Aliquam neque ligula, rutrum at tincidunt ut, fringilla posuere risus. Aenean porta convallis turpis, et ornare nisl finibus ac. Maecenas volutpat tortor vel sagittis aliquam.",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Expectation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Nam ut justo id nisl egestas mattis.Proin ac ipsum eget velit varius pretium.Nam porta ligula vitae diam auctor dictum.Nulla varius nunc in velit ultrices ullamcorper.",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JobOfferId = 13,
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Offer = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas in lacus id ex iaculis iaculis vel ac metus.Morbi ut tellus accumsan, vehicula mi volutpat, lobortis leo.Aenean sodales massa ac risus tincidunt, in malesuada est tincidunt.Donec eget turpis tincidunt, tempus erat at, venenatis erat.Duis ultricies dui ac tempor placerat.Cras sollicitudin ligula in turpis aliquam luctus at quis lacus.",
                            Responsibilities = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem lorem, volutpat facilisis fringilla et, molestie in nunc. Cras ac nunc imperdiet, euismod lorem vitae, maximus nulla. Etiam porttitor elit vitae purus dapibus consectetur. Fusce imperdiet turpis a lectus scelerisque, vel ultrices odio vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque nisi nisl, fringilla in luctus eget, cursus congue augue. Integer condimentum sollicitudin nunc in tristique. Integer id justo leo. Morbi vel lacus sagittis, venenatis ex eget, porta risus. Nunc suscipit dignissim magna at commodo. Sed iaculis, turpis quis ornare luctus, massa orci tempor tellus, consequat gravida nisi nibh et dui. Integer eu metus sem. Morbi auctor ex est, vel aliquam arcu vulputate eu. Fusce aliquam eros quis ipsum iaculis aliquet. Nullam et auctor lorem, sit amet tempor lorem. Praesent nec nisl in ipsum accumsan sollicitudin.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 14,
                            About = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id viverra erat. Nulla euismod laoreet metus vitae mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla maximus libero non elementum congue. Vestibulum dignissim pellentesque mauris non molestie. Aliquam neque ligula, rutrum at tincidunt ut, fringilla posuere risus. Aenean porta convallis turpis, et ornare nisl finibus ac. Maecenas volutpat tortor vel sagittis aliquam.",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Expectation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Nam ut justo id nisl egestas mattis.Proin ac ipsum eget velit varius pretium.Nam porta ligula vitae diam auctor dictum.Nulla varius nunc in velit ultrices ullamcorper.",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JobOfferId = 14,
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Offer = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas in lacus id ex iaculis iaculis vel ac metus.Morbi ut tellus accumsan, vehicula mi volutpat, lobortis leo.Aenean sodales massa ac risus tincidunt, in malesuada est tincidunt.Donec eget turpis tincidunt, tempus erat at, venenatis erat.Duis ultricies dui ac tempor placerat.Cras sollicitudin ligula in turpis aliquam luctus at quis lacus.",
                            Responsibilities = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem lorem, volutpat facilisis fringilla et, molestie in nunc. Cras ac nunc imperdiet, euismod lorem vitae, maximus nulla. Etiam porttitor elit vitae purus dapibus consectetur. Fusce imperdiet turpis a lectus scelerisque, vel ultrices odio vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque nisi nisl, fringilla in luctus eget, cursus congue augue. Integer condimentum sollicitudin nunc in tristique. Integer id justo leo. Morbi vel lacus sagittis, venenatis ex eget, porta risus. Nunc suscipit dignissim magna at commodo. Sed iaculis, turpis quis ornare luctus, massa orci tempor tellus, consequat gravida nisi nibh et dui. Integer eu metus sem. Morbi auctor ex est, vel aliquam arcu vulputate eu. Fusce aliquam eros quis ipsum iaculis aliquet. Nullam et auctor lorem, sit amet tempor lorem. Praesent nec nisl in ipsum accumsan sollicitudin.",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 15,
                            About = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id viverra erat. Nulla euismod laoreet metus vitae mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla maximus libero non elementum congue. Vestibulum dignissim pellentesque mauris non molestie. Aliquam neque ligula, rutrum at tincidunt ut, fringilla posuere risus. Aenean porta convallis turpis, et ornare nisl finibus ac. Maecenas volutpat tortor vel sagittis aliquam.",
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            Expectation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Nam ut justo id nisl egestas mattis.Proin ac ipsum eget velit varius pretium.Nam porta ligula vitae diam auctor dictum.Nulla varius nunc in velit ultrices ullamcorper.",
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            JobOfferId = 15,
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 167, DateTimeKind.Unspecified).AddTicks(6028), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            Offer = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas in lacus id ex iaculis iaculis vel ac metus.Morbi ut tellus accumsan, vehicula mi volutpat, lobortis leo.Aenean sodales massa ac risus tincidunt, in malesuada est tincidunt.Donec eget turpis tincidunt, tempus erat at, venenatis erat.Duis ultricies dui ac tempor placerat.Cras sollicitudin ligula in turpis aliquam luctus at quis lacus.",
                            Responsibilities = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem lorem, volutpat facilisis fringilla et, molestie in nunc. Cras ac nunc imperdiet, euismod lorem vitae, maximus nulla. Etiam porttitor elit vitae purus dapibus consectetur. Fusce imperdiet turpis a lectus scelerisque, vel ultrices odio vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque nisi nisl, fringilla in luctus eget, cursus congue augue. Integer condimentum sollicitudin nunc in tristique. Integer id justo leo. Morbi vel lacus sagittis, venenatis ex eget, porta risus. Nunc suscipit dignissim magna at commodo. Sed iaculis, turpis quis ornare luctus, massa orci tempor tellus, consequat gravida nisi nibh et dui. Integer eu metus sem. Morbi auctor ex est, vel aliquam arcu vulputate eu. Fusce aliquam eros quis ipsum iaculis aliquet. Nullam et auctor lorem, sit amet tempor lorem. Praesent nec nisl in ipsum accumsan sollicitudin.",
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("JobsCatalog.Domain.Entities.JobOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceLevelId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Inactivated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Modified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgrammingLanguageId")
                        .HasColumnType("int");

                    b.Property<int>("SalaryMax")
                        .HasColumnType("int");

                    b.Property<int>("SalaryMin")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ExperienceLevelId");

                    b.HasIndex("ProgrammingLanguageId");

                    b.ToTable("JobOffers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Wroclaw",
                            CompanyId = 1,
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            ExperienceLevelId = 1,
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            PositionName = "Junior .Net Developer",
                            ProgrammingLanguageId = 1,
                            SalaryMax = 8000,
                            SalaryMin = 6000,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            City = "Wroclaw",
                            CompanyId = 2,
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            ExperienceLevelId = 2,
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            PositionName = ".Net Developer",
                            ProgrammingLanguageId = 1,
                            SalaryMax = 15000,
                            SalaryMin = 10000,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 3,
                            City = "Wroclaw",
                            CompanyId = 3,
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            ExperienceLevelId = 3,
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            PositionName = "Senior .Net Developer",
                            ProgrammingLanguageId = 1,
                            SalaryMax = 20000,
                            SalaryMin = 15000,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 4,
                            City = "Warsaw",
                            CompanyId = 2,
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            ExperienceLevelId = 2,
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            PositionName = "Java Developer",
                            ProgrammingLanguageId = 2,
                            SalaryMax = 15000,
                            SalaryMin = 10000,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 5,
                            City = "Warsaw",
                            CompanyId = 2,
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            ExperienceLevelId = 3,
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            PositionName = "Senior Java Developer",
                            ProgrammingLanguageId = 2,
                            SalaryMax = 20000,
                            SalaryMin = 15000,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 6,
                            City = "Warsaw",
                            CompanyId = 2,
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            ExperienceLevelId = 4,
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            PositionName = "Java Tech Lead",
                            ProgrammingLanguageId = 2,
                            SalaryMax = 30000,
                            SalaryMin = 20000,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 7,
                            City = "Remote",
                            CompanyId = 3,
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            ExperienceLevelId = 2,
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            PositionName = ".Net Developer",
                            ProgrammingLanguageId = 1,
                            SalaryMax = 15000,
                            SalaryMin = 10000,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 8,
                            City = "Poznan",
                            CompanyId = 3,
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            ExperienceLevelId = 2,
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            PositionName = "Python Developer",
                            ProgrammingLanguageId = 3,
                            SalaryMax = 15000,
                            SalaryMin = 10000,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 9,
                            City = "Remote",
                            CompanyId = 4,
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            ExperienceLevelId = 4,
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            PositionName = "C++ Tech Lead",
                            ProgrammingLanguageId = 5,
                            SalaryMax = 30000,
                            SalaryMin = 20000,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 10,
                            City = "Poznan",
                            CompanyId = 4,
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            ExperienceLevelId = 1,
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            PositionName = "Junior JavaScript Developer",
                            ProgrammingLanguageId = 4,
                            SalaryMax = 8000,
                            SalaryMin = 6000,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 11,
                            City = "Gdansk",
                            CompanyId = 4,
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            ExperienceLevelId = 3,
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            PositionName = "Senior JavaScript Developer",
                            ProgrammingLanguageId = 4,
                            SalaryMax = 20000,
                            SalaryMin = 15000,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 12,
                            City = "Katowice",
                            CompanyId = 4,
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            ExperienceLevelId = 4,
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            PositionName = "Java Tech Lead",
                            ProgrammingLanguageId = 2,
                            SalaryMax = 30000,
                            SalaryMin = 20000,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 13,
                            City = "Crakow",
                            CompanyId = 5,
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            ExperienceLevelId = 4,
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            PositionName = ".Net Tech Lead",
                            ProgrammingLanguageId = 1,
                            SalaryMax = 30000,
                            SalaryMin = 20000,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 14,
                            City = "Remote",
                            CompanyId = 5,
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            ExperienceLevelId = 2,
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            PositionName = "Python Developer",
                            ProgrammingLanguageId = 3,
                            SalaryMax = 15000,
                            SalaryMin = 10000,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 15,
                            City = "Crakow",
                            CompanyId = 5,
                            Created = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Admin",
                            ExperienceLevelId = 2,
                            Inactivated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Modified = new DateTimeOffset(new DateTime(2022, 3, 12, 15, 25, 45, 166, DateTimeKind.Unspecified).AddTicks(4036), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedBy = "Admin",
                            PositionName = "JavaScript Developer",
                            ProgrammingLanguageId = 4,
                            SalaryMax = 15000,
                            SalaryMin = 10000,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("JobsCatalog.Domain.Helper.JobOfferTechnology", b =>
                {
                    b.Property<int>("JobOfferId")
                        .HasColumnType("int");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("int");

                    b.HasKey("JobOfferId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("JobOfferTechnologies");

                    b.HasData(
                        new
                        {
                            JobOfferId = 1,
                            TechnologyId = 1
                        },
                        new
                        {
                            JobOfferId = 1,
                            TechnologyId = 2
                        },
                        new
                        {
                            JobOfferId = 1,
                            TechnologyId = 3
                        },
                        new
                        {
                            JobOfferId = 2,
                            TechnologyId = 1
                        },
                        new
                        {
                            JobOfferId = 2,
                            TechnologyId = 2
                        },
                        new
                        {
                            JobOfferId = 2,
                            TechnologyId = 3
                        },
                        new
                        {
                            JobOfferId = 2,
                            TechnologyId = 14
                        },
                        new
                        {
                            JobOfferId = 2,
                            TechnologyId = 15
                        },
                        new
                        {
                            JobOfferId = 3,
                            TechnologyId = 1
                        },
                        new
                        {
                            JobOfferId = 3,
                            TechnologyId = 2
                        },
                        new
                        {
                            JobOfferId = 3,
                            TechnologyId = 3
                        },
                        new
                        {
                            JobOfferId = 3,
                            TechnologyId = 14
                        },
                        new
                        {
                            JobOfferId = 3,
                            TechnologyId = 15
                        },
                        new
                        {
                            JobOfferId = 4,
                            TechnologyId = 10
                        },
                        new
                        {
                            JobOfferId = 4,
                            TechnologyId = 11
                        },
                        new
                        {
                            JobOfferId = 4,
                            TechnologyId = 12
                        },
                        new
                        {
                            JobOfferId = 4,
                            TechnologyId = 13
                        },
                        new
                        {
                            JobOfferId = 4,
                            TechnologyId = 2
                        },
                        new
                        {
                            JobOfferId = 5,
                            TechnologyId = 10
                        },
                        new
                        {
                            JobOfferId = 5,
                            TechnologyId = 11
                        },
                        new
                        {
                            JobOfferId = 5,
                            TechnologyId = 12
                        },
                        new
                        {
                            JobOfferId = 5,
                            TechnologyId = 13
                        },
                        new
                        {
                            JobOfferId = 5,
                            TechnologyId = 2
                        },
                        new
                        {
                            JobOfferId = 6,
                            TechnologyId = 10
                        },
                        new
                        {
                            JobOfferId = 6,
                            TechnologyId = 11
                        },
                        new
                        {
                            JobOfferId = 6,
                            TechnologyId = 12
                        },
                        new
                        {
                            JobOfferId = 6,
                            TechnologyId = 13
                        },
                        new
                        {
                            JobOfferId = 6,
                            TechnologyId = 2
                        },
                        new
                        {
                            JobOfferId = 6,
                            TechnologyId = 6
                        },
                        new
                        {
                            JobOfferId = 6,
                            TechnologyId = 7
                        },
                        new
                        {
                            JobOfferId = 7,
                            TechnologyId = 1
                        },
                        new
                        {
                            JobOfferId = 7,
                            TechnologyId = 2
                        },
                        new
                        {
                            JobOfferId = 7,
                            TechnologyId = 3
                        },
                        new
                        {
                            JobOfferId = 7,
                            TechnologyId = 14
                        },
                        new
                        {
                            JobOfferId = 7,
                            TechnologyId = 15
                        },
                        new
                        {
                            JobOfferId = 7,
                            TechnologyId = 6
                        },
                        new
                        {
                            JobOfferId = 7,
                            TechnologyId = 7
                        },
                        new
                        {
                            JobOfferId = 8,
                            TechnologyId = 17
                        },
                        new
                        {
                            JobOfferId = 8,
                            TechnologyId = 18
                        },
                        new
                        {
                            JobOfferId = 8,
                            TechnologyId = 2
                        },
                        new
                        {
                            JobOfferId = 8,
                            TechnologyId = 7
                        },
                        new
                        {
                            JobOfferId = 8,
                            TechnologyId = 16
                        },
                        new
                        {
                            JobOfferId = 9,
                            TechnologyId = 19
                        },
                        new
                        {
                            JobOfferId = 10,
                            TechnologyId = 4
                        },
                        new
                        {
                            JobOfferId = 10,
                            TechnologyId = 5
                        },
                        new
                        {
                            JobOfferId = 10,
                            TechnologyId = 8
                        },
                        new
                        {
                            JobOfferId = 10,
                            TechnologyId = 9
                        },
                        new
                        {
                            JobOfferId = 11,
                            TechnologyId = 10
                        },
                        new
                        {
                            JobOfferId = 11,
                            TechnologyId = 11
                        },
                        new
                        {
                            JobOfferId = 11,
                            TechnologyId = 12
                        },
                        new
                        {
                            JobOfferId = 11,
                            TechnologyId = 13
                        },
                        new
                        {
                            JobOfferId = 11,
                            TechnologyId = 6
                        },
                        new
                        {
                            JobOfferId = 11,
                            TechnologyId = 7
                        },
                        new
                        {
                            JobOfferId = 11,
                            TechnologyId = 16
                        },
                        new
                        {
                            JobOfferId = 12,
                            TechnologyId = 1
                        },
                        new
                        {
                            JobOfferId = 12,
                            TechnologyId = 2
                        },
                        new
                        {
                            JobOfferId = 12,
                            TechnologyId = 3
                        },
                        new
                        {
                            JobOfferId = 12,
                            TechnologyId = 14
                        },
                        new
                        {
                            JobOfferId = 12,
                            TechnologyId = 15
                        },
                        new
                        {
                            JobOfferId = 12,
                            TechnologyId = 6
                        },
                        new
                        {
                            JobOfferId = 12,
                            TechnologyId = 7
                        },
                        new
                        {
                            JobOfferId = 12,
                            TechnologyId = 16
                        },
                        new
                        {
                            JobOfferId = 13,
                            TechnologyId = 1
                        },
                        new
                        {
                            JobOfferId = 13,
                            TechnologyId = 2
                        },
                        new
                        {
                            JobOfferId = 13,
                            TechnologyId = 3
                        },
                        new
                        {
                            JobOfferId = 13,
                            TechnologyId = 14
                        },
                        new
                        {
                            JobOfferId = 13,
                            TechnologyId = 15
                        },
                        new
                        {
                            JobOfferId = 13,
                            TechnologyId = 6
                        },
                        new
                        {
                            JobOfferId = 13,
                            TechnologyId = 7
                        },
                        new
                        {
                            JobOfferId = 14,
                            TechnologyId = 17
                        },
                        new
                        {
                            JobOfferId = 14,
                            TechnologyId = 18
                        },
                        new
                        {
                            JobOfferId = 14,
                            TechnologyId = 2
                        },
                        new
                        {
                            JobOfferId = 14,
                            TechnologyId = 7
                        },
                        new
                        {
                            JobOfferId = 14,
                            TechnologyId = 16
                        },
                        new
                        {
                            JobOfferId = 15,
                            TechnologyId = 4
                        },
                        new
                        {
                            JobOfferId = 15,
                            TechnologyId = 5
                        },
                        new
                        {
                            JobOfferId = 15,
                            TechnologyId = 8
                        },
                        new
                        {
                            JobOfferId = 15,
                            TechnologyId = 9
                        });
                });

            modelBuilder.Entity("JobsCatalog.Domain.Entities.JobDescription", b =>
                {
                    b.HasOne("JobsCatalog.Domain.Entities.JobOffer", "JobOffer")
                        .WithOne("JobDescription")
                        .HasForeignKey("JobsCatalog.Domain.Entities.JobDescription", "JobOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobOffer");
                });

            modelBuilder.Entity("JobsCatalog.Domain.Entities.JobOffer", b =>
                {
                    b.HasOne("JobsCatalog.Domain.Entities.Company", "Company")
                        .WithMany("JobOffers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobsCatalog.Domain.Dictionaries.ExperienceLevel", "ExperienceLevel")
                        .WithMany("JobOffers")
                        .HasForeignKey("ExperienceLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobsCatalog.Domain.Dictionaries.ProgrammingLanguage", "ProgrammingLanguage")
                        .WithMany("JobOffers")
                        .HasForeignKey("ProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ExperienceLevel");

                    b.Navigation("ProgrammingLanguage");
                });

            modelBuilder.Entity("JobsCatalog.Domain.Helper.JobOfferTechnology", b =>
                {
                    b.HasOne("JobsCatalog.Domain.Entities.JobOffer", "JobOffer")
                        .WithMany("JobOfferTechnology")
                        .HasForeignKey("JobOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobsCatalog.Domain.Dictionaries.Technology", "Technology")
                        .WithMany("JobOfferTechnology")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobOffer");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("JobsCatalog.Domain.Dictionaries.ExperienceLevel", b =>
                {
                    b.Navigation("JobOffers");
                });

            modelBuilder.Entity("JobsCatalog.Domain.Dictionaries.ProgrammingLanguage", b =>
                {
                    b.Navigation("JobOffers");
                });

            modelBuilder.Entity("JobsCatalog.Domain.Dictionaries.Technology", b =>
                {
                    b.Navigation("JobOfferTechnology");
                });

            modelBuilder.Entity("JobsCatalog.Domain.Entities.Company", b =>
                {
                    b.Navigation("JobOffers");
                });

            modelBuilder.Entity("JobsCatalog.Domain.Entities.JobOffer", b =>
                {
                    b.Navigation("JobDescription");

                    b.Navigation("JobOfferTechnology");
                });
#pragma warning restore 612, 618
        }
    }
}
